# Generated by Django 3.1.6 on 2021-02-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210227_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_pl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_pl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='title_pl',
        ),
    ]
